jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Prepare local.properties for testing
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew clean build
    - continue-on-error: true
      name: Deploy snapshot
      run: ./gradlew uploadArchives --no-daemon --no-parallel -PSONATYPE_NEXUS_USERNAME=${{secrets.SONATYPE_NEXUS_USERNAME}}
        -PSONATYPE_NEXUS_PASSWORD=${{secrets.SONATYPE_NEXUS_PASSWORD}} -Psigning.keyId=${{secrets.SIGNING_KEY_ID}}
        -Psigning.password=${{secrets.SIGNING_PASSWORD}} -Psigning.secretKeyRingFile=$(echo
        ~/.gradle/secring.gpg)
name: Deploy snapshot
on:
  repository_dispatch:
    types: trigger-ga___deploy_snapshot.yml
